<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from nmregistry/xml/schema/CRM/Nmregistry/NmregistryReminderSent.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:486a0c4e86f6561c7525f851469327d0)
 */
use CRM_Nmregistry_ExtensionUtil as E;

/**
 * Database access object for the NmregistryReminderSent entity.
 */
class CRM_Nmregistry_DAO_NmregistryReminderSent extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_nmregistry_reminder_sent';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique NmregistryReminderSent ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * FK to Contact to whom reminder was sent
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $contact_id;

  /**
   * Reminder was sent because this date (e.g. 'last updated profile') matched the reminder 'days' criteria.
   *
   * @var string
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $compare_date_time;

  /**
   * Value of 'days' criteria for the reminder when it was sent.
   *
   * @var int|string
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $days;

  /**
   * Date and time when reminder was sent.
   *
   * @var string|null
   *   (SQL type: datetime)
   *   Note that values will be retrieved from the database as a string.
   */
  public $sent_date_time;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_nmregistry_reminder_sent';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Nmregistry Reminder Sents') : E::ts('Nmregistry Reminder Sent');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'contact_id', 'civicrm_contact', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique NmregistryReminderSent ID'),
          'required' => TRUE,
          'where' => 'civicrm_nmregistry_reminder_sent.id',
          'table_name' => 'civicrm_nmregistry_reminder_sent',
          'entity' => 'NmregistryReminderSent',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminderSent',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'contact_id' => [
          'name' => 'contact_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to Contact to whom reminder was sent'),
          'where' => 'civicrm_nmregistry_reminder_sent.contact_id',
          'table_name' => 'civicrm_nmregistry_reminder_sent',
          'entity' => 'NmregistryReminderSent',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminderSent',
          'localizable' => 0,
          'FKClassName' => 'CRM_Contact_DAO_Contact',
          'add' => NULL,
        ],
        'compare_date_time' => [
          'name' => 'compare_date_time',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Compare Date Time'),
          'description' => E::ts('Reminder was sent because this date (e.g. \'last updated profile\') matched the reminder \'days\' criteria.'),
          'required' => TRUE,
          'where' => 'civicrm_nmregistry_reminder_sent.compare_date_time',
          'table_name' => 'civicrm_nmregistry_reminder_sent',
          'entity' => 'NmregistryReminderSent',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminderSent',
          'localizable' => 0,
          'add' => NULL,
        ],
        'days' => [
          'name' => 'days',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Days'),
          'description' => E::ts('Value of \'days\' criteria for the reminder when it was sent.'),
          'required' => TRUE,
          'where' => 'civicrm_nmregistry_reminder_sent.days',
          'table_name' => 'civicrm_nmregistry_reminder_sent',
          'entity' => 'NmregistryReminderSent',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminderSent',
          'localizable' => 0,
          'add' => NULL,
        ],
        'sent_date_time' => [
          'name' => 'sent_date_time',
          'type' => CRM_Utils_Type::T_DATE + CRM_Utils_Type::T_TIME,
          'title' => E::ts('Sent Date Time'),
          'description' => E::ts('Date and time when reminder was sent.'),
          'where' => 'civicrm_nmregistry_reminder_sent.sent_date_time',
          'default' => 'CURRENT_TIMESTAMP',
          'table_name' => 'civicrm_nmregistry_reminder_sent',
          'entity' => 'NmregistryReminderSent',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminderSent',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'nmregistry_reminder_sent', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'nmregistry_reminder_sent', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [
      'nmregistryremindersent_compare_date_time' => [
        'name' => 'nmregistryremindersent_compare_date_time',
        'field' => [
          0 => 'compare_date_time',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_nmregistry_reminder_sent::0::compare_date_time',
      ],
      'nmregistryremindersent_days' => [
        'name' => 'nmregistryremindersent_days',
        'field' => [
          0 => 'days',
        ],
        'localizable' => FALSE,
        'sig' => 'civicrm_nmregistry_reminder_sent::0::days',
      ],
    ];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
