<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from nmregistry/xml/schema/CRM/Nmregistry/NmregistryReminder.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:103260835336ccdfe23f824ba73ba75d)
 */
use CRM_Nmregistry_ExtensionUtil as E;

/**
 * Database access object for the NmregistryReminder entity.
 */
class CRM_Nmregistry_DAO_NmregistryReminder extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_nmregistry_reminder';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Unique NmregistryReminder ID
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $id;

  /**
   * Human name to identify this reminder in administrative interface.
   *
   * @var string
   *   (SQL type: varchar(255))
   *   Note that values will be retrieved from the database as a string.
   */
  public $name;

  /**
   * JSON storage of sending criteria for this reminder
   *
   * @var string
   *   (SQL type: text)
   *   Note that values will be retrieved from the database as a string.
   */
  public $criteria;

  /**
   * FK to msg_template
   *
   * @var int|string|null
   *   (SQL type: int unsigned)
   *   Note that values will be retrieved from the database as a string.
   */
  public $msg_template_id;

  /**
   * Set registry profile status to 'archived' when this reminder runs?
   *
   * @var bool|string
   *   (SQL type: tinyint)
   *   Note that values will be retrieved from the database as a string.
   */
  public $is_archive;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_nmregistry_reminder';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Nmregistry Reminders') : E::ts('Nmregistry Reminder');
  }

  /**
   * Returns foreign keys and entity references.
   *
   * @return array
   *   [CRM_Core_Reference_Interface]
   */
  public static function getReferenceColumns() {
    if (!isset(Civi::$statics[__CLASS__]['links'])) {
      Civi::$statics[__CLASS__]['links'] = static::createReferenceColumns(__CLASS__);
      Civi::$statics[__CLASS__]['links'][] = new CRM_Core_Reference_Basic(self::getTableName(), 'msg_template_id', 'civicrm_msg_template', 'id');
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'links_callback', Civi::$statics[__CLASS__]['links']);
    }
    return Civi::$statics[__CLASS__]['links'];
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'id' => [
          'name' => 'id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Unique NmregistryReminder ID'),
          'required' => TRUE,
          'where' => 'civicrm_nmregistry_reminder.id',
          'table_name' => 'civicrm_nmregistry_reminder',
          'entity' => 'NmregistryReminder',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminder',
          'localizable' => 0,
          'html' => [
            'type' => 'Number',
          ],
          'readonly' => TRUE,
          'add' => NULL,
        ],
        'name' => [
          'name' => 'name',
          'type' => CRM_Utils_Type::T_STRING,
          'title' => E::ts('Name'),
          'description' => E::ts('Human name to identify this reminder in administrative interface.'),
          'required' => TRUE,
          'maxlength' => 255,
          'size' => CRM_Utils_Type::HUGE,
          'where' => 'civicrm_nmregistry_reminder.name',
          'table_name' => 'civicrm_nmregistry_reminder',
          'entity' => 'NmregistryReminder',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminder',
          'localizable' => 0,
          'add' => NULL,
        ],
        'criteria' => [
          'name' => 'criteria',
          'type' => CRM_Utils_Type::T_TEXT,
          'title' => E::ts('Criteria'),
          'description' => E::ts('JSON storage of sending criteria for this reminder'),
          'required' => TRUE,
          'where' => 'civicrm_nmregistry_reminder.criteria',
          'table_name' => 'civicrm_nmregistry_reminder',
          'entity' => 'NmregistryReminder',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminder',
          'localizable' => 0,
          'add' => NULL,
        ],
        'msg_template_id' => [
          'name' => 'msg_template_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('FK to msg_template'),
          'where' => 'civicrm_nmregistry_reminder.msg_template_id',
          'table_name' => 'civicrm_nmregistry_reminder',
          'entity' => 'NmregistryReminder',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminder',
          'localizable' => 0,
          'FKClassName' => 'CRM_Core_DAO_MessageTemplate',
          'add' => NULL,
        ],
        'is_archive' => [
          'name' => 'is_archive',
          'type' => CRM_Utils_Type::T_BOOLEAN,
          'description' => E::ts('Set registry profile status to \'archived\' when this reminder runs?'),
          'required' => TRUE,
          'where' => 'civicrm_nmregistry_reminder.is_archive',
          'default' => '0',
          'table_name' => 'civicrm_nmregistry_reminder',
          'entity' => 'NmregistryReminder',
          'bao' => 'CRM_Nmregistry_DAO_NmregistryReminder',
          'localizable' => 0,
          'add' => '4.6',
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'nmregistry_reminder', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'nmregistry_reminder', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
