-- +--------------------------------------------------------------------+
-- | Copyright CiviCRM LLC. All rights reserved.                        |
-- |                                                                    |
-- | This work is published under the GNU AGPLv3 license with some      |
-- | permitted exceptions and without any warranty. For full license    |
-- | and copyright information, see https://civicrm.org/licensing       |
-- +--------------------------------------------------------------------+
--
-- Generated from schema.tpl
-- DO NOT EDIT.  Generated by CRM_Core_CodeGen
--
-- /*******************************************************
-- *
-- * Clean up the existing tables - this section generated from drop.tpl
-- *
-- *******************************************************/

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS `civicrm_nmregistry_reminder`;

SET FOREIGN_KEY_CHECKS=1;
-- /*******************************************************
-- *
-- * Create new tables
-- *
-- *******************************************************/

-- /*******************************************************
-- *
-- * civicrm_nmregistry_reminder
-- *
-- * Automoted reminders for nmregistry
-- *
-- *******************************************************/
CREATE TABLE `civicrm_nmregistry_reminder` (
  `id` int unsigned NOT NULL AUTO_INCREMENT COMMENT 'Unique NmregistryReminder ID',
  `name` varchar(255) NOT NULL COMMENT 'Human name to identify this reminder in administrative interface.',
  `days_after` int unsigned NOT NULL COMMENT 'How many days after last-profile-update should this reminder run?',
  `msg_template_id` int unsigned COMMENT 'FK to msg_template',
  `is_final` tinyint NOT NULL DEFAULT 0 COMMENT 'Set registry profile status to \'archived\' when this reminder runs?',
  PRIMARY KEY (`id`),
  CONSTRAINT FK_civicrm_nmregistry_reminder_msg_template_id FOREIGN KEY (`msg_template_id`) REFERENCES `civicrm_msg_template`(`id`) ON DELETE SET NULL
)
ENGINE=InnoDB;
